// swift-tools-version:6.0
//
// Version-specific manifest, selected automatically by SwiftPM on any Swift 6.0+
// toolchain. Swift 5.9 and 5.10 toolchains do not see this file at all and use
// `Package.swift` (tools-version 5.9), which is what keeps the 5.9 floor real.
//
// It exists for one reason: to compile this SDK's own targets in **Swift 6
// language mode**, so the full strict-concurrency rules are enforced as errors
// rather than deferred. That cannot be expressed in the 5.9 manifest —
// `.swiftLanguageMode` requires tools-version 6.0 — and the alternatives are
// worse. `-Xswiftc -swift-version 6` applies to every target in the graph
// including swift-nio and async-http-client, which are not built for it; and
// `.unsafeFlags` makes a package unusable as a dependency at all, which would
// break every consumer to make a compiler setting.
//
// The language mode is set per target below, so it governs THIS package's
// sources and nothing else in the dependency graph.
//
// Everything below other than those `swiftSettings` must stay identical to
// `Package.swift`. `PackageManifestParityTests` fails the build if it does not.
import PackageDescription

let package = Package(
    name: "AxiamSDK",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "AxiamSDK", targets: ["AxiamSDK"]),
    ],
    dependencies: [
        // HTTP client with cross-platform TLS + client-cert mTLS via NIOSSL.
        // (URLSession client certs need Apple's Security.framework and don't work on Linux.)
        .package(url: "https://github.com/swift-server/async-http-client.git", from: "1.21.0"),
        // TLSConfiguration: certificate chain / private key from PEM, custom CA trust roots.
        .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.25.0"),
        // EdDSA / Ed25519 JWKS signature verification.
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.2.0"),
        // Core NIO — used directly by the SDK for ByteBuffer and by the test HTTP server.
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.62.0"),
        // DocC static-site generation for the GitHub Pages docs workflow.
        // Build-tool plugin only — not linked into the AxiamSDK product.
        .package(url: "https://github.com/apple/swift-docc-plugin.git", from: "1.3.0"),
    ],
    targets: [
        .target(
            name: "AxiamSDK",
            dependencies: [
                .product(name: "AsyncHTTPClient", package: "async-http-client"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "Crypto", package: "swift-crypto"),
                // RSASSA-PSS (PS256) for DPoP proof verification — CONTRACT.md §21.7.2
                // check 2. `Crypto` covers Ed25519 and P-256; RSA-PSS lives in
                // _CryptoExtras, the same swift-crypto package, so this adds a product
                // rather than a dependency.
                .product(name: "_CryptoExtras", package: "swift-crypto"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
            ],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "AxiamSDKTests",
            dependencies: [
                "AxiamSDK",
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "Crypto", package: "swift-crypto"),
            ],
            // CONTRACT.md §22.13's reference vectors, generated by the server's
            // own reactor sign path. They travel with the suite so §22
            // conformance needs no broker, no server and no network.
            resources: [.copy("Support/reactor_v2_reference_vectors.json")]
            // Deliberately WITHOUT the Swift 6 language-mode setting — the only
            // target here that is. The library and every example compile clean under Swift 6
            // language mode; the test target does not, in 48 places across 19
            // files, and all of them are test-harness plumbing rather than
            // anything the shipped SDK does:
            //
            //   - NSLock.lock()/unlock() called inside async test doubles
            //     (MockTransport, ScriptedTransport, RefreshProbeTransport), which
            //     Swift 6 makes unavailable from asynchronous contexts;
            //   - `[String: Any]` JSON fixtures and XCTestCase `self` captured in
            //     the @Sendable handler closures those doubles take;
            //   - `[String: Any]` fixtures held as static properties.
            //
            // Scoping the mode to the targets that actually ship is the honest
            // split: it makes "this SDK is data-race-safe under full checking" a
            // claim about the artifact consumers get, proven on every build, rather
            // than one blocked behind a rewrite of the test harness. Migrating the
            // suite is real work with no product-behaviour change, and belongs in
            // its own change where the diff can be reviewed as what it is.
            //
            // VersionPolicyTests pins this arrangement so it cannot drift silently
            // in either direction.
        ),
        // Runnable, self-contained examples (see Examples/README.md). These are
        // executable targets, not library products, so downstream consumers that
        // depend on the `AxiamSDK` product never build them.
        .executableTarget(
            name: "LoginMFAExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/LoginMFA",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "OpaqueLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/OpaqueLogin",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "RestAuthzExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/RestAuthz",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "OidcLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/OidcLogin",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "DeviceLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/DeviceLogin",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "TokenExchangeExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/TokenExchange",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "UmaResourceServerExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/UmaResourceServer",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "UmaClientExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/UmaClient",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "WebauthnPasskeysExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/WebauthnPasskeys",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "AccountLifecycleExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/AccountLifecycle",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "ParLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/ParLogin",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "ReactorExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/Reactor",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "VersionCompatibilityExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/VersionCompatibility",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .executableTarget(
            name: "TelemetryHookExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/TelemetryHook",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
