// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "AxiamSDK",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "AxiamSDK", targets: ["AxiamSDK"]),
    ],
    dependencies: [
        // HTTP client with cross-platform TLS + client-cert mTLS via NIOSSL.
        // (URLSession client certs need Apple's Security.framework and don't work on Linux.)
        .package(url: "https://github.com/swift-server/async-http-client.git", from: "1.21.0"),
        // TLSConfiguration: certificate chain / private key from PEM, custom CA trust roots.
        .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.25.0"),
        // EdDSA / Ed25519 JWKS signature verification.
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.2.0"),
        // Core NIO — used directly by the SDK for ByteBuffer and by the test HTTP server.
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.62.0"),
        // DocC static-site generation for the GitHub Pages docs workflow.
        // Build-tool plugin only — not linked into the AxiamSDK product.
        .package(url: "https://github.com/apple/swift-docc-plugin.git", from: "1.3.0"),
    ],
    targets: [
        .target(
            name: "AxiamSDK",
            dependencies: [
                .product(name: "AsyncHTTPClient", package: "async-http-client"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "Crypto", package: "swift-crypto"),
                // RSASSA-PSS (PS256) for DPoP proof verification — CONTRACT.md §21.7.2
                // check 2. `Crypto` covers Ed25519 and P-256; RSA-PSS lives in
                // _CryptoExtras, the same swift-crypto package, so this adds a product
                // rather than a dependency.
                .product(name: "_CryptoExtras", package: "swift-crypto"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
            ]
        ),
        .testTarget(
            name: "AxiamSDKTests",
            dependencies: [
                "AxiamSDK",
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "NIOSSL", package: "swift-nio-ssl"),
                .product(name: "Crypto", package: "swift-crypto"),
            ],
            // CONTRACT.md §22.13's reference vectors, generated by the server's
            // own reactor sign path. They travel with the suite so §22
            // conformance needs no broker, no server and no network.
            resources: [.copy("Support/reactor_v2_reference_vectors.json")]
        ),
        // Runnable, self-contained examples (see Examples/README.md). These are
        // executable targets, not library products, so downstream consumers that
        // depend on the `AxiamSDK` product never build them.
        .executableTarget(
            name: "LoginMFAExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/LoginMFA"
        ),
        .executableTarget(
            name: "OpaqueLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/OpaqueLogin"
        ),
        .executableTarget(
            name: "RestAuthzExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/RestAuthz"
        ),
        .executableTarget(
            name: "OidcLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/OidcLogin"
        ),
        .executableTarget(
            name: "DeviceLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/DeviceLogin"
        ),
        .executableTarget(
            name: "TokenExchangeExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/TokenExchange"
        ),
        .executableTarget(
            name: "UmaResourceServerExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/UmaResourceServer"
        ),
        .executableTarget(
            name: "UmaClientExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/UmaClient"
        ),
        .executableTarget(
            name: "WebauthnPasskeysExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/WebauthnPasskeys"
        ),
        .executableTarget(
            name: "AccountLifecycleExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/AccountLifecycle"
        ),
        .executableTarget(
            name: "ParLoginExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/ParLogin"
        ),
        .executableTarget(
            name: "ReactorExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/Reactor"
        ),
        .executableTarget(
            name: "VersionCompatibilityExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/VersionCompatibility"
        ),
        // CONTRACT.md §27: the management API. ManagementBasics covers the imperative
        // surface and the §27.4 rules that are easy to get wrong; ManagementManifest covers
        // the §27.6/§27.7 declarative layer built with the @resultBuilder DSL;
        // DeviceMtlsProvisioning is the flow the certificate namespaces exist for —
        // provision an IoT device end to end, then let it authenticate over §6.1 mTLS.
        .executableTarget(
            name: "ManagementBasicsExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/ManagementBasics"
        ),
        .executableTarget(
            name: "ManagementManifestExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/ManagementManifest"
        ),
        .executableTarget(
            name: "DeviceMtlsProvisioningExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/DeviceMtlsProvisioning"
        ),
        .executableTarget(
            name: "TelemetryHookExample",
            dependencies: ["AxiamSDK"],
            path: "Examples/TelemetryHook"
        ),
    ]
)
