import Crypto
import Foundation
import XCTest

@testable import AxiamSDK

/// Reactor — CONTRACT.md §22, run against the committed §22.13 reference vectors.
///
/// The vectors are generated by the AXIAM server's own sign path, so these are
/// not "does my implementation agree with itself" tests: a byte out of place in
/// the canonical form produces a MAC that differs from a number the server
/// computed, and the test says so.
///
/// THE THREE PLACES A §22 PORT ACTUALLY BREAKS, all covered below:
///
/// 1. `hmac_signature` is serialized as **null** INSIDE the signed bytes, not
///    omitted as §8's own two message types omit it. An encoder will drop or
///    reorder that null, which is why both canonical forms are built by hand.
/// 2. `reason`, `patch` and `require_mfa` are OMITTED when absent or false. A
///    reply that serializes `"require_mfa": false` produces different bytes and
///    therefore a different MAC — reproduce the omission rule, not the values.
/// 3. Freshness is two-sided. A future timestamp is not "extra fresh"; it is the
///    shape of a captured message held for later.
final class ReactorTests: XCTestCase {

    // MARK: - Fixtures

    private static let loadedVectors: [String: Any] = {
        guard let url = Bundle.module.url(
            forResource: "reactor_v2_reference_vectors", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else {
            fatalError("the §22.13 reference vectors are missing from the test bundle")
        }
        return root
    }()

    private var vectors: [String: Any] { Self.loadedVectors }

    private func node(_ path: String...) -> [String: Any] {
        var current = vectors
        for key in path {
            guard let next = current[key] as? [String: Any] else {
                XCTFail("missing vector node \(path.joined(separator: "."))")
                return [:]
            }
            current = next
        }
        return current
    }

    /// The tenant's derived AMQP subkey (§8.1) as RAW BYTES — the vectors publish
    /// it in hex, and signing the hex string instead of the bytes is a MAC that
    /// will never verify against anything the server produced.
    private var signingKey: Sensitive<Data> {
        let hex = node("hkdf")["derived_subkey_hex"] as! String
        var bytes = Data()
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            bytes.append(UInt8(hex[index..<next], radix: 16)!)
            index = next
        }
        return Sensitive(bytes)
    }

    private var tenantID: String { vectors["tenant_id"] as! String }
    private var correlationID: String { vectors["expected_correlation_id"] as! String }
    private var reactorID: String { vectors["reactor_id"] as! String }

    /// The instant the vectors were signed, so freshness passes deterministically.
    /// A suite that used the real clock would start failing on a date nobody chose.
    private var verifiedAt: Date { ReactorTime.parse(vectors["verified_at"] as! String)! }

    /// The wire body: the committed message, serialized with sorted keys — which
    /// is what the server's BTreeMap emits, and the one place a library dump is
    /// safe here.
    private func wireBody(_ vector: [String: Any]) -> Data {
        try! JSONSerialization.data(
            withJSONObject: vector["message"] as! [String: Any],
            options: [.sortedKeys, .withoutEscapingSlashes])
    }

    /// Sign an event body the way the SERVER does, so a test can build a validly
    /// signed variant and isolate one defect at a time.
    ///
    /// Written out longhand rather than borrowed from the SDK on purpose: a test
    /// that signed through the code under test could not tell a canonical-form bug
    /// from agreement with itself. What proves this signer right is that the
    /// committed vectors reproduce under it — asserted below.
    private func signEvent(_ message: [String: Any]) -> Data {
        func quoted(_ s: String) -> String {
            String(data: try! JSONSerialization.data(
                withJSONObject: [s], options: [.withoutEscapingSlashes]), encoding: .utf8)!
                .dropFirst().dropLast().description
        }
        let payload = String(
            data: try! JSONSerialization.data(
                withJSONObject: message["payload"]!,
                options: [.sortedKeys, .withoutEscapingSlashes]),
            encoding: .utf8)!
        var canonical = "{"
        canonical += "\"tenant_id\":\(quoted(message["tenant_id"] as! String)),"
        canonical += "\"event\":\(quoted(message["event"] as! String)),"
        canonical += "\"correlation_id\":\(quoted(message["correlation_id"] as! String)),"
        canonical += "\"payload\":\(payload),"
        canonical += "\"timeout_ms\":\(message["timeout_ms"] as! Int),"
        canonical += "\"key_version\":\(message["key_version"] as! Int),"
        canonical += "\"nonce\":\(quoted(message["nonce"] as! String)),"
        canonical += "\"issued_at\":\(quoted(message["issued_at"] as! String)),"
        canonical += "\"hmac_signature\":null}"

        var mac = HMAC<SHA256>(key: SymmetricKey(data: signingKey.wrapped))
        mac.update(data: Data(canonical.utf8))
        let hex = Array(mac.finalize()).map { String(format: "%02x", $0) }.joined()

        var signed = message
        signed["hmac_signature"] = hex
        return try! JSONSerialization.data(
            withJSONObject: signed, options: [.sortedKeys, .withoutEscapingSlashes])
    }

    /// The committed event vector, re-stamped and re-signed.
    private func eventAt(_ issuedAt: String, nonce: String? = nil) -> Data {
        var message = node("server_to_reactor", "login_post_auth")["message"] as! [String: Any]
        message["issued_at"] = issuedAt
        if let nonce { message["nonce"] = nonce }
        return signEvent(message)
    }

    private func decision(from outcome: [String: Any]) -> ReactorDecision {
        switch outcome["kind"] as! String {
        case "deny": return .deny(outcome["reason"] as? String ?? "")
        case "mutate": return .mutate(outcome["patch"] as! [String: String])
        // The vectors spell the step-up answer as its own `kind`, which is
        // exactly the shape §22.4 says it is NOT: `require_mfa` rides on `allow`
        // rather than being a fourth decision value, and the canonical bytes show
        // that.
        case "require_mfa": return .allowWithStepUp
        default: return .allow
        }
    }

    private func pinnedConfig(nonce: String = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
        -> ReactorConfig
    {
        let at = verifiedAt
        return ReactorConfig(
            tenantID: tenantID, reactorID: reactorID, signingKey: signingKey,
            clock: { at }, nonceSource: { nonce })
    }

    // MARK: - §22.13 sign direction

    func testEveryCommittedReplyVectorReproducesItsBytesAndMAC() throws {
        let replies = node("reactor_to_server")
        for (name, raw) in replies {
            let vector = raw as! [String: Any]
            let message = vector["message"] as! [String: Any]
            let event = ReactorEventName(rawValue: message["event"] as! String)!
            let answer = decision(from: vector["expected_outcome"] as! [String: Any])

            let canonical = ReactorProtocol.canonicalReply(
                correlationID: correlationID, tenantID: tenantID, event: event,
                decision: answer, nonce: message["nonce"] as! String,
                issuedAt: message["issued_at"] as! String)
            XCTAssertEqual(
                canonical, vector["canonical_signed_json"] as! String,
                "canonical bytes differ for the \(name) vector")

            let wire = try ReactorProtocol.buildReply(
                signingKey: signingKey, correlationID: correlationID, tenantID: tenantID,
                event: event, decision: answer, nonce: message["nonce"] as! String,
                issuedAt: message["issued_at"] as! String)
            let parsed = try JSONSerialization.jsonObject(with: Data(wire.utf8)) as! [String: Any]
            XCTAssertEqual(
                parsed["hmac_signature"] as? String, vector["hmac_signature_hex"] as? String,
                "MAC differs for the \(name) vector")
        }
    }

    func testRequireMFAIsOmittedWhenFalse() {
        // The omission changes the canonical bytes and therefore the MAC. An
        // implementation that reproduces the values but not the omission rule
        // passes every "is the field right" assertion and fails every real reply.
        let plain = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .loginPostAuth,
            decision: .allow, nonce: "n", issuedAt: "2026-07-10T12:00:00Z")
        XCTAssertFalse(plain.contains("require_mfa"))

        let stepUp = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .loginPostAuth,
            decision: .allowWithStepUp, nonce: "n", issuedAt: "2026-07-10T12:00:00Z")
        XCTAssertTrue(stepUp.contains("\"require_mfa\":true"))
    }

    func testReasonAndPatchAreOmittedWhenAbsent() {
        let allow = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .tokenPreIssue,
            decision: .allow, nonce: "n", issuedAt: "2026-07-10T12:00:00Z")
        XCTAssertFalse(allow.contains("reason"))
        XCTAssertFalse(allow.contains("patch"))

        // A deny with no reason still denies; the server substitutes "denied by
        // reactor". An empty reason is omitted, not sent as "".
        let bare = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .loginPostAuth,
            decision: .deny(""), nonce: "n", issuedAt: "2026-07-10T12:00:00Z")
        XCTAssertFalse(bare.contains("reason"))
        XCTAssertTrue(bare.contains("\"decision\":\"deny\""))
    }

    func testTheNonceIsInsideTheSignedBytes() throws {
        // Two replies differing only in `nonce` carry different MACs — the
        // nonce_binding vector pair, checked against the server's own numbers.
        // The pair is the `allow` reply with only its nonce changed.
        let binding = node("nonce_binding")
        let a = try ReactorProtocol.buildReply(
            signingKey: signingKey, correlationID: correlationID, tenantID: tenantID,
            event: .loginPostAuth, decision: .allow,
            nonce: binding["nonce_a"] as! String, issuedAt: "2026-07-10T12:00:00Z")
        let b = try ReactorProtocol.buildReply(
            signingKey: signingKey, correlationID: correlationID, tenantID: tenantID,
            event: .loginPostAuth, decision: .allow,
            nonce: binding["nonce_b"] as! String, issuedAt: "2026-07-10T12:00:00Z")

        let parsedA = try JSONSerialization.jsonObject(with: Data(a.utf8)) as! [String: Any]
        let parsedB = try JSONSerialization.jsonObject(with: Data(b.utf8)) as! [String: Any]
        XCTAssertEqual(parsedA["hmac_signature"] as? String, binding["hmac_a_hex"] as? String)
        XCTAssertEqual(parsedB["hmac_signature"] as? String, binding["hmac_b_hex"] as? String)
        XCTAssertNotEqual(binding["hmac_a_hex"] as? String, binding["hmac_b_hex"] as? String)
    }

    func testAMutateNeverBecomesAllowPlusPatch() {
        let canonical = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .tokenPreIssue,
            decision: .mutate(["ext.department": "eng"]), nonce: "n",
            issuedAt: "2026-07-10T12:00:00Z")
        XCTAssertTrue(canonical.contains("\"decision\":\"mutate\""))
        XCTAssertFalse(canonical.contains("\"decision\":\"allow\""))
    }

    func testAForbiddenPatchKeyIsSentUnfiltered() {
        // §22.4 rule 1 / §22.10 rule 3. One forbidden key rejects the WHOLE patch
        // server-side, including the fields that would have been fine — and
        // dropping the offender to rescue the rest would leave the author
        // believing a field was set when it was dropped.
        let canonical = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .tokenPreIssue,
            decision: .mutate(["ext.department": "eng", "sub": "attacker"]),
            nonce: "n", issuedAt: "2026-07-10T12:00:00Z")
        XCTAssertTrue(canonical.contains("\"sub\":\"attacker\""))
        // And the SDK knows perfectly well it is forbidden — it just does not act
        // on that knowledge when building the reply.
        XCTAssertFalse(ReactorEventName.tokenPreIssue.allowsPatchField("sub"))
    }

    func testAPatchIsEmittedInByteOrder() {
        // Swift's dictionary order is not stable between runs, so a patch left in
        // its own order would produce a MAC that verifies only sometimes — the
        // worst possible failure mode.
        let canonical = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .tokenPreIssue,
            decision: .mutate(["ext.zulu": "z", "ext.alpha": "a", "ext.mike": "m"]),
            nonce: "n", issuedAt: "2026-07-10T12:00:00Z")
        let alpha = canonical.range(of: "ext.alpha")!.lowerBound
        let mike = canonical.range(of: "ext.mike")!.lowerBound
        let zulu = canonical.range(of: "ext.zulu")!.lowerBound
        XCTAssertTrue(alpha < mike)
        XCTAssertTrue(mike < zulu)
    }

    func testStringEscapingIsSerdeJsons() throws {
        // The two mandatory escapes, the five short forms, \u00XX for the
        // remaining control characters — and NOTHING else. A forward slash stays
        // literal and UTF-8 passes through unescaped, which is where a naive port
        // diverges and produces a MAC the server will not accept.
        let reason = "a \"quoted\" \\ back\nline\ttab\r\u{08}\u{0C} / slash \u{01} ünïcode"
        let canonical = ReactorProtocol.canonicalReply(
            correlationID: correlationID, tenantID: tenantID, event: .loginPostAuth,
            decision: .deny(reason), nonce: "n", issuedAt: "2026-07-10T12:00:00Z")

        XCTAssertTrue(canonical.contains("\\\"quoted\\\""))
        XCTAssertTrue(canonical.contains("\\n"))
        XCTAssertTrue(canonical.contains("\\t"))
        XCTAssertTrue(canonical.contains("\\r"))
        XCTAssertTrue(canonical.contains("\\b"))
        XCTAssertTrue(canonical.contains("\\f"))
        XCTAssertTrue(canonical.contains("\\u0001"))
        XCTAssertFalse(canonical.contains("\\/"))
        XCTAssertTrue(canonical.contains("ünïcode"))

        // And it is still parseable JSON that round-trips to the same string.
        let parsed = try JSONSerialization.jsonObject(
            with: Data(canonical.utf8)) as! [String: Any]
        XCTAssertEqual(parsed["reason"] as? String, reason)
    }

    func testRequireMFAOnAnyOtherEventIsRefused() {
        // Refused rather than corrected: the result is NO REPLY, and the
        // registration's failure_policy decides.
        XCTAssertThrowsError(
            try ReactorProtocol.buildReply(
                signingKey: signingKey, correlationID: correlationID, tenantID: tenantID,
                event: .tokenPreIssue, decision: .allowWithStepUp, nonce: "n",
                issuedAt: "2026-07-10T12:00:00Z")
        ) { error in
            XCTAssertEqual(
                error as? ReactorReplyError, .requireMFAOnWrongEvent(.tokenPreIssue))
        }
    }

    func testAnEmptyMutateIsRefused() {
        XCTAssertThrowsError(
            try ReactorProtocol.buildReply(
                signingKey: signingKey, correlationID: correlationID, tenantID: tenantID,
                event: .tokenPreIssue, decision: .mutate([:]), nonce: "n",
                issuedAt: "2026-07-10T12:00:00Z")
        ) { error in
            XCTAssertEqual(error as? ReactorReplyError, .emptyMutation)
        }
    }

    // MARK: - §22.13 verify direction

    func testTheTestSignerReproducesTheCommittedVectors() throws {
        // The premise of every re-signed case below. If this fails, those tests
        // are agreeing with a bug rather than with the server.
        let vector = node("server_to_reactor", "login_post_auth")
        let resigned = try JSONSerialization.jsonObject(
            with: signEvent(vector["message"] as! [String: Any])) as! [String: Any]
        XCTAssertEqual(
            resigned["hmac_signature"] as? String, vector["hmac_signature_hex"] as? String)
    }

    func testEveryCommittedEventVectorVerifies() {
        var seen: [String: Date] = [:]
        for (name, raw) in node("server_to_reactor") {
            let vector = raw as! [String: Any]
            let result = ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: wireBody(vector), expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen)
            guard case .success(let event) = result else {
                XCTFail("the \(name) vector did not verify: \(result)")
                continue
            }
            XCTAssertEqual(
                event.event.rawValue,
                (vector["message"] as! [String: Any])["event"] as? String)
            XCTAssertEqual(event.correlationID, correlationID)
        }
    }

    func testAnEventFailsUnderAnyOtherKey() {
        var seen: [String: Date] = [:]
        let result = ReactorProtocol.verifyEvent(
            signingKey: Sensitive(Data(repeating: 1, count: 32)),
            body: wireBody(node("server_to_reactor", "login_post_auth")),
            expectedTenantID: tenantID, now: verifiedAt, seenNonces: &seen)
        XCTAssertEqual(result.refusal, .badSignature)
    }

    func testTamperingWithAnySignedFieldInvalidatesTheEvent() {
        for field in ["payload", "timeout_ms", "tenant_id", "nonce"] {
            var message = node("server_to_reactor", "login_post_auth")["message"]
                as! [String: Any]
            switch field {
            case "timeout_ms":
                message["timeout_ms"] = (message["timeout_ms"] as! Int) + 1
            case "payload":
                var payload = message["payload"] as! [String: Any]
                payload["sub"] = "mallory"
                message["payload"] = payload
            default:
                message[field] = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
            }
            let body = try! JSONSerialization.data(
                withJSONObject: message, options: [.sortedKeys, .withoutEscapingSlashes])
            var seen: [String: Date] = [:]
            let result = ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen)
            XCTAssertEqual(result.refusal, .badSignature, "tampering with \(field) was accepted")
        }
    }

    func testKeyVersionBelowTwoIsRefusedBeforeTheSignature() {
        var message = node("server_to_reactor", "login_post_auth")["message"] as! [String: Any]
        message["key_version"] = 1
        let body = try! JSONSerialization.data(
            withJSONObject: message, options: [.sortedKeys, .withoutEscapingSlashes])
        var seen: [String: Date] = [:]
        // Not badSignature: the version check comes first, and reporting it as a
        // signature failure would send an operator looking at the wrong key.
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen).refusal,
            .keyVersionTooOld)
    }

    func testFreshnessIsRefusedInBothDirections() {
        let body = wireBody(node("server_to_reactor", "login_post_auth"))
        let skew = Double(vectors["freshness_skew_secs"] as! Int)
        var seen: [String: Date] = [:]

        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt.addingTimeInterval(skew + 1), seenNonces: &seen).refusal,
            .stale)

        // A future timestamp is not "extra fresh" — it is the shape of a captured
        // message held for later.
        seen = [:]
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt.addingTimeInterval(-skew - 1), seenNonces: &seen).refusal,
            .stale)

        // And the boundary itself is inside the window.
        seen = [:]
        XCTAssertNil(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt.addingTimeInterval(skew), seenNonces: &seen).refusal)
    }

    func testARepeatedNonceIsRefusedAsAReplay() {
        let body = wireBody(node("server_to_reactor", "login_post_auth"))
        var seen: [String: Date] = [:]
        XCTAssertNil(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen).refusal)
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen).refusal,
            .replay)
    }

    func testAnEventForAnotherTenantIsRefusedAfterTheMAC() {
        var seen: [String: Date] = [:]
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey,
                body: wireBody(node("server_to_reactor", "login_post_auth")),
                expectedTenantID: "99999999-9999-9999-9999-999999999999",
                now: verifiedAt, seenNonces: &seen).refusal,
            .tenantMismatch)
    }

    func testAnUnregisteredOperationIsRefusedAfterTheMAC() {
        // Also how §22.7's exclusion refuses: those operations are in no registry,
        // so a delivery naming one never reaches a handler. Validly signed, so the
        // registry check is what actually fires.
        var message = node("server_to_reactor", "login_post_auth")["message"] as! [String: Any]
        message["event"] = "authz.check"
        var seen: [String: Date] = [:]
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: signEvent(message), expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen).refusal,
            .unknownEvent)
    }

    func testAnUnparseableIssuedAtIsMalformedNotStale() {
        // Validly signed, so the MAC is not the defect — a body that got past the
        // MAC and still carries a timestamp nobody can read is malformed, not
        // late, and saying "stale" would send an operator to check clock drift.
        var seen: [String: Date] = [:]
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: eventAt("yesterday"), expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen).refusal,
            .malformed)
    }

    func testABodyMissingASignedFieldIsMalformed() {
        for field in ["tenant_id", "event", "correlation_id", "payload", "timeout_ms",
                      "nonce", "issued_at"] {
            var message = node("server_to_reactor", "login_post_auth")["message"]
                as! [String: Any]
            message.removeValue(forKey: field)
            let body = try! JSONSerialization.data(
                withJSONObject: message, options: [.sortedKeys, .withoutEscapingSlashes])
            var seen: [String: Date] = [:]
            XCTAssertEqual(
                ReactorProtocol.verifyEvent(
                    signingKey: signingKey, body: body, expectedTenantID: tenantID,
                    now: verifiedAt, seenNonces: &seen).refusal,
                .malformed, "a body missing \(field) was not malformed")
        }
    }

    func testABodyThatIsNotJSONIsMalformed() {
        var seen: [String: Date] = [:]
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: Data("<html>".utf8), expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen).refusal,
            .malformed)
    }

    func testAnEventWithNoSignatureAtAllIsRefused() {
        var message = node("server_to_reactor", "login_post_auth")["message"] as! [String: Any]
        message.removeValue(forKey: "hmac_signature")
        let body = try! JSONSerialization.data(
            withJSONObject: message, options: [.sortedKeys, .withoutEscapingSlashes])
        var seen: [String: Date] = [:]
        XCTAssertEqual(
            ReactorProtocol.verifyEvent(
                signingKey: signingKey, body: body, expectedTenantID: tenantID,
                now: verifiedAt, seenNonces: &seen).refusal,
            .badSignature)
    }

    func testTheCorrelationReplayVectorDoesNotTransfer() throws {
        // The accepted reply verbatim — valid signature, inside the freshness
        // window — presented against a different in-flight event. The
        // correlation_id is inside the signed bytes, so re-signing for the other
        // event is what an attacker cannot do.
        let replay = node("rejected_replies", "correlation_replay")
        let message = replay["message"] as! [String: Any]
        let forOther = try ReactorProtocol.buildReply(
            signingKey: signingKey,
            correlationID: replay["verify_against_correlation_id"] as! String,
            tenantID: tenantID,
            event: ReactorEventName(rawValue: message["event"] as! String)!,
            decision: .allow, nonce: message["nonce"] as! String,
            issuedAt: message["issued_at"] as! String)
        let parsed = try JSONSerialization.jsonObject(with: Data(forOther.utf8))
            as! [String: Any]
        XCTAssertNotEqual(
            parsed["hmac_signature"] as? String, replay["hmac_signature_hex"] as? String)
    }

    // MARK: - §22.5 the registry and its allow-lists

    func testTokenPreIssueAdmitsTheExtNamespaceAndNothingElse() {
        let event = ReactorEventName.tokenPreIssue
        XCTAssertTrue(event.allowsPatchField("ext.department"))
        XCTAssertTrue(event.allowsPatchField("ext.a.b.c"))
        // `ext.` names the namespace, not a claim.
        XCTAssertFalse(event.allowsPatchField("ext."))
        XCTAssertFalse(event.allowsPatchField("ext"))
        // A prefix match on the string is not a match on the namespace.
        XCTAssertFalse(event.allowsPatchField("extra"))
        XCTAssertFalse(event.allowsPatchField("external_id"))
        XCTAssertFalse(event.allowsPatchField("evil.ext.department"))
        // Every standard claim, because none begins with `ext.` — which is the
        // whole design: a hook that could rewrite `sub` could mint a token for
        // anyone.
        for claim in ["sub", "aud", "exp", "iat", "iss", "scope", "tenant_id"] {
            XCTAssertFalse(event.allowsPatchField(claim), "\(claim) must be unreachable")
        }
    }

    func testUserPreCreateAdmitsItsFieldsAndItsNamespace() {
        let event = ReactorEventName.userPreCreate
        XCTAssertTrue(event.allowsPatchField("email"))
        XCTAssertTrue(event.allowsPatchField("username"))
        XCTAssertTrue(event.allowsPatchField("metadata.source"))
        XCTAssertFalse(event.allowsPatchField("metadata"))  // the bare namespace
        XCTAssertFalse(event.allowsPatchField("password"))
        XCTAssertFalse(event.allowsPatchField("tenant_id"))
        XCTAssertFalse(event.allowsPatchField("roles"))
    }

    func testTheVetoOnlyEventsAcceptNoPatchField() {
        for event in [ReactorEventName.loginPostAuth, .grantPreAssign] {
            for field in ["email", "ext.department", "metadata.source", "anything"] {
                XCTAssertFalse(event.allowsPatchField(field))
            }
            XCTAssertTrue(event.mutableFields.isEmpty)
        }
    }

    func testTheHotPathOperationsAreAbsentFromEveryExposedConstant() {
        // §22.7 is a normative MUST NOT, and §22.13 says to assert on the enum
        // rather than on a comment. A reactor round trip is milliseconds; the
        // check path's budget is microseconds.
        let names = ReactorEventName.allCases.map(\.rawValue)
        XCTAssertEqual(names.count, 5)
        XCTAssertFalse(names.contains("authz.check"))
        XCTAssertFalse(names.contains("authz.check_batch"))
        XCTAssertFalse(names.contains("token.introspect"))
        XCTAssertNil(ReactorEventName(rawValue: "authz.check"))
    }

    func testTheStrictestDefaultWinsInEitherOrder() {
        XCTAssertEqual(ReactorFailurePolicy.strictestDefault(for: [.tokenPreIssue]), .failOpen)
        XCTAssertEqual(ReactorFailurePolicy.strictestDefault(for: [.loginPostAuth]), .failClosed)
        // Both orders, because reducing this to "take the first event's default"
        // would let the order of a JSON array decide whether an unreachable fraud
        // check passes.
        XCTAssertEqual(
            ReactorFailurePolicy.strictestDefault(for: [.tokenPreIssue, .loginPostAuth]),
            .failClosed)
        XCTAssertEqual(
            ReactorFailurePolicy.strictestDefault(for: [.loginPostAuth, .tokenPreIssue]),
            .failClosed)
        // An empty registration is not "nothing to fail at".
        XCTAssertEqual(ReactorFailurePolicy.strictestDefault(for: []), .failClosed)
    }

    func testTheTopologyNamesMatchTheVectors() {
        let topology = node("topology")
        XCTAssertEqual(
            ReactorTopology.queueName(tenantID: tenantID, reactorID: reactorID),
            topology["queue"] as? String)
        XCTAssertEqual(
            ReactorTopology.routingKey(tenantID: tenantID, event: .loginPostAuth),
            topology["routing_key_login_post_auth"] as? String)
    }

    // MARK: - §22.10 the runtime

    func testTheRuntimeVerifiesDispatchesAndPublishes() async throws {
        let transport = RecordingReactorTransport(
            bodies: [wireBody(node("server_to_reactor", "login_post_auth"))],
            replyTo: "amq.rabbitmq.reply-to.abc")
        let seenEvent = Box<String?>(nil)

        try await reactorServe(config: pinnedConfig(), transport: transport) { event in
            seenEvent.value = event.event.rawValue
            return .allow
        }

        XCTAssertEqual(seenEvent.value, "login.post_auth")
        let published = await transport.published
        XCTAssertEqual(published.count, 1)
        XCTAssertEqual(published[0].destination, "amq.rabbitmq.reply-to.abc")
        XCTAssertEqual(published[0].correlationID, correlationID)

        let reply = try JSONSerialization.jsonObject(with: published[0].body) as! [String: Any]
        XCTAssertEqual(reply["decision"] as? String, "allow")
        XCTAssertEqual(reply["key_version"] as? Int, 2)
        XCTAssertNotNil(reply["hmac_signature"] as? String)
    }

    func testAHandlerThatThrowsProducesNoReply() async throws {
        // §22.10 rule 2, asserted as a COUNT rather than as an absent `allow`: a
        // runtime that answered on behalf of a handler that threw would have
        // overridden the operator's fail_closed setting from inside the library.
        let transport = RecordingReactorTransport(
            bodies: [wireBody(node("server_to_reactor", "login_post_auth"))])
        try await reactorServe(config: pinnedConfig(), transport: transport) { _ in
            throw AxiamError.network(NetworkError("handler blew up"))
        }
        let published = await transport.published
        XCTAssertTrue(published.isEmpty)
    }

    func testAnUnverifiableDeliveryProducesNoReply() async throws {
        var message = node("server_to_reactor", "login_post_auth")["message"] as! [String: Any]
        var payload = message["payload"] as! [String: Any]
        payload["sub"] = "mallory"
        message["payload"] = payload
        let body = try JSONSerialization.data(
            withJSONObject: message, options: [.sortedKeys, .withoutEscapingSlashes])

        let transport = RecordingReactorTransport(bodies: [body])
        let ran = Box(false)
        try await reactorServe(config: pinnedConfig(), transport: transport) { _ in
            ran.value = true
            return .allow
        }
        // And the handler never saw it: a runtime that hands unverified bytes to
        // user code has already lost, because the handler will act on them.
        XCTAssertFalse(ran.value)
        let published = await transport.published
        XCTAssertTrue(published.isEmpty)
    }

    func testAnAbstainingHandlerProducesNoReply() async throws {
        let transport = RecordingReactorTransport(
            bodies: [wireBody(node("server_to_reactor", "login_post_auth"))])
        try await reactorServe(config: pinnedConfig(), transport: transport) { _ in nil }
        let published = await transport.published
        XCTAssertTrue(published.isEmpty)
    }

    func testAReplyTheBuilderRefusesProducesNoReply() async throws {
        // require_mfa on token.pre_issue. The runtime's own error, and rule 2
        // applies to it exactly as to a handler that threw.
        let transport = RecordingReactorTransport(
            bodies: [wireBody(node("server_to_reactor", "token_pre_issue"))])
        try await reactorServe(config: pinnedConfig(), transport: transport) { _ in
            .allowWithStepUp
        }
        let published = await transport.published
        XCTAssertTrue(published.isEmpty)
    }

    func testTheRuntimeKeepsOneNonceSetForItsWholeLifetime() async throws {
        // Building a fresh set per delivery defeats replay dedup entirely, and the
        // only way to see the difference is to feed the same delivery twice.
        let body = wireBody(node("server_to_reactor", "login_post_auth"))
        let transport = RecordingReactorTransport(bodies: [body, body])
        let dispatches = Box(0)
        try await reactorServe(config: pinnedConfig(), transport: transport) { _ in
            dispatches.value += 1
            return .allow
        }
        XCTAssertEqual(dispatches.value, 1)
        let published = await transport.published
        XCTAssertEqual(published.count, 1)
    }

    func testTheRuntimeDefaultsAreTheRealClockAndARealNonceSource() async throws {
        // The clock and nonce seams exist for §22.13's pinned vectors. A config
        // that sets neither must still work — and the way to see that is a freshly
        // stamped event, which only passes if the runtime is reading the wall
        // clock.
        let now = ReactorTime.format(Date())
        let transport = RecordingReactorTransport(bodies: [
            eventAt(now, nonce: "11111111-1111-1111-1111-111111111111"),
            eventAt(now, nonce: "22222222-2222-2222-2222-222222222222"),
        ])
        let config = ReactorConfig(
            tenantID: tenantID, reactorID: reactorID, signingKey: signingKey)

        let dispatches = Box(0)
        try await reactorServe(config: config, transport: transport) { _ in
            dispatches.value += 1
            return .allow
        }
        // The complement of the replay test: the seen-set must not turn every
        // second delivery away, which is what a set keyed on something other than
        // the nonce would do.
        XCTAssertEqual(dispatches.value, 2)

        let published = await transport.published
        XCTAssertEqual(published.count, 2)
        let reply = try JSONSerialization.jsonObject(with: published[0].body) as! [String: Any]
        XCTAssertEqual((reply["nonce"] as! String).count, 36)
        XCTAssertNotEqual(reply["nonce"] as? String, "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
        XCTAssertEqual((reply["issued_at"] as! String).count, 20)
    }

    func testTheReplyNeverCarriesTheSigningKey() async throws {
        let transport = RecordingReactorTransport(
            bodies: [wireBody(node("server_to_reactor", "login_post_auth"))])
        try await reactorServe(config: pinnedConfig(), transport: transport) { _ in
            .deny("nope")
        }
        let published = await transport.published
        XCTAssertEqual(published.count, 1)
        let text = String(data: published[0].body, encoding: .utf8)!
        XCTAssertFalse(text.contains(node("hkdf")["derived_subkey_hex"] as! String))

        // §22.12: the tenant AMQP signing key is a credential, exactly as §8's key
        // already is. It must not appear at any log level, nor in a reconnect
        // diagnostic.
        XCTAssertEqual("\(signingKey)", "[SENSITIVE]")
    }

    // MARK: - §22.14.1 the binder

    func testRouterTwoEventsReachTheirOwnHandlers() async throws {
        let reached = Box<String?>(nil)
        var router = ReactorRouter()
        try router.on(.loginPostAuth) { _ in
            reached.value = "login"
            return .allow
        }
        try router.on(.tokenPreIssue) { _ in
            reached.value = "token"
            return .allow
        }
        let handler = router.handler()

        _ = try await handler(event(named: .loginPostAuth))
        XCTAssertEqual(reached.value, "login")
        _ = try await handler(event(named: .tokenPreIssue))
        XCTAssertEqual(reached.value, "token")
    }

    func testRouterANameOutsideTheRegistryIsRefusedAtBindTime() {
        // Rule 2. Failing when the binding is written is the entire point: a typo
        // that survives to production is discovered as silence, and silence on a
        // fail_open event is indistinguishable from a healthy reactor with nothing
        // to say.
        var router = ReactorRouter()
        XCTAssertThrowsError(try router.on(eventNamed: "login.postauth") { _ in .allow }) {
            XCTAssertEqual($0 as? ReactorBindingError, .unknownEvent("login.postauth"))
        }
    }

    func testRouterAHotPathOperationIsRefusedLikeAnyUnknownName() {
        // §22.7's three are in no registry row, so they fail rule 2 exactly as a
        // typo does. There is deliberately no separate hot-path list to produce a
        // more specific error — that list would be a constant naming them, which
        // §22.13's hot-path assertion forbids outright.
        var router = ReactorRouter()
        for hot in ["authz.check", "authz.check_batch", "token.introspect"] {
            XCTAssertThrowsError(try router.on(eventNamed: hot) { _ in .allow }) {
                XCTAssertEqual($0 as? ReactorBindingError, .unknownEvent(hot))
            }
        }
    }

    func testRouterASecondBindingIsAnErrorNotAnOverwrite() throws {
        // Rule 3. Which of two handlers runs is not something the author of either
        // can see from their own file.
        var router = ReactorRouter()
        try router.on(.loginPostAuth) { _ in .allow }
        XCTAssertThrowsError(try router.on(.loginPostAuth) { _ in .deny("second") }) {
            XCTAssertEqual($0 as? ReactorBindingError, .duplicateBinding(.loginPostAuth))
        }
    }

    func testRouterAnUnboundEventAbstains() async throws {
        // Rule 4, and the reason this subsection exists. It is not answered
        // `allow`, and not answered `deny` either: the binder does not know what
        // the registration was for, and the operator's policy does.
        var router = ReactorRouter()
        try router.on(.loginPostAuth) { _ in .allow }
        let handler = router.handler()

        let answer = try await handler(event(named: .userPreCreate))
        XCTAssertNil(answer)

        // And through the runtime, where abstention means zero published messages.
        let transport = RecordingReactorTransport(
            bodies: [wireBody(node("server_to_reactor", "token_pre_issue"))])
        try await reactorServe(config: pinnedConfig(), transport: transport, handler: handler)
        let published = await transport.published
        XCTAssertTrue(published.isEmpty)
    }

    func testRouterAnExplicitFallbackIsHonouredAndHasNoDefault() async throws {
        var router = ReactorRouter()
        let fellBack = Box(false)
        router.fallback { _ in
            fellBack.value = true
            return .deny("unhandled by this reactor")
        }

        let answer = try await router.handler()(event(named: .userPreCreate))
        XCTAssertTrue(fellBack.value)
        XCTAssertEqual(answer, .deny("unhandled by this reactor"))
    }

    func testRouterAHandlersOwnFailurePropagatesUnchanged() async throws {
        // Rule 5. §22.10 rule 2 puts the fail-closed obligation on the runtime,
        // and a binder that swallowed a failure before the runtime saw it would
        // satisfy the letter of that rule while defeating it.
        var router = ReactorRouter()
        try router.on(.loginPostAuth) { _ in
            throw AxiamError.network(NetworkError("handler blew up"))
        }
        do {
            _ = try await router.handler()(event(named: .loginPostAuth))
            XCTFail("the handler's error must reach the runtime")
        } catch {
            // Reached, which is the assertion.
        }
    }

    func testRouterAPatchIsNotFilteredOnItsWayThrough() async throws {
        // Rule 6. A binder sits between the handler and the runtime and is
        // therefore the newest place to be tempted into "helpfully" pruning a
        // forbidden key.
        var router = ReactorRouter()
        try router.on(.tokenPreIssue) { _ in
            .mutate(["ext.department": "eng", "sub": "attacker"])
        }
        let answer = try await router.handler()(event(named: .tokenPreIssue))
        guard case .mutate(let patch) = answer else {
            XCTFail("expected a mutation")
            return
        }
        XCTAssertEqual(patch.count, 2)
        XCTAssertEqual(patch["sub"], "attacker")
    }

    func testRouterReportsTheEventsItBound() throws {
        var router = ReactorRouter()
        try router.on(.tokenPreIssue) { _ in .allow }
        try router.on(.loginPostAuth) { _ in .allow }
        XCTAssertEqual(router.boundEvents.count, 2)
        // So the author can compute §22.8's default from the code that actually
        // handles the events rather than from a restatement of the registration.
        XCTAssertEqual(
            ReactorFailurePolicy.strictestDefault(for: router.boundEvents), .failClosed)
    }

    // MARK: - §8b rules 1–5

    func testAmqpsGuardAcceptsAndParsesAnAmqpsURL() throws {
        let endpoint = try amqpsEndpoint("amqps://broker.internal:5671/prod")
        XCTAssertEqual(endpoint.host, "broker.internal")
        XCTAssertEqual(endpoint.port, 5671)
        XCTAssertEqual(endpoint.virtualHost, "prod")
        XCTAssertEqual(endpoint.url, "amqps://broker.internal:5671/prod")
    }

    func testAmqpsGuardDefaultsThePortAndVhost() throws {
        let endpoint = try amqpsEndpoint("amqps://broker.internal")
        XCTAssertEqual(endpoint.port, 5671)
        XCTAssertEqual(endpoint.virtualHost, "/")
    }

    func testAmqpsGuardRefusesPlaintextAndEveryOtherScheme() {
        // Rule 1, and rule 5's posture: a failed amqps:// connection is an error to
        // surface, not a condition to work around — so there is no way to express a
        // plaintext fallback here at all.
        for url in ["amqp://broker:5672", "http://broker", "https://broker",
                    "amqps.evil://broker", "broker:5671", "", "amqpss://broker"] {
            XCTAssertThrowsError(try amqpsEndpoint(url), "\(url) must be refused")
        }
    }

    func testAmqpsGuardHasNoLoopbackException() throws {
        // §8b rule 8. §6's http://localhost dev carve-out does not extend to the
        // broker URL — they are different rules, and the server has no plaintext
        // listener for such an exception to reach.
        for url in ["amqp://localhost:5672", "amqp://127.0.0.1:5672", "amqp://[::1]:5672"] {
            XCTAssertThrowsError(try amqpsEndpoint(url), "\(url) must be refused")
        }
        // And the TLS form of the same hosts is fine.
        XCTAssertNoThrow(try amqpsEndpoint("amqps://localhost:5671"))
    }

    func testAmqpsGuardIsCaseInsensitiveOnTheScheme() {
        XCTAssertNoThrow(try amqpsEndpoint("AMQPS://broker.internal"))
    }

    func testAmqpsGuardHalfAClientIdentityFailsClosed() throws {
        // Rule 3. Connecting without the mutual half would present no client
        // identity at all while the caller believes one was configured.
        XCTAssertThrowsError(
            try amqpsEndpoint("amqps://broker", clientCertificatePEM: "CERT")
        ) { XCTAssertEqual($0 as? AmqpsEndpointError, .incompleteClientIdentity) }
        XCTAssertThrowsError(
            try amqpsEndpoint("amqps://broker", clientKeyPEM: "KEY")
        ) { XCTAssertEqual($0 as? AmqpsEndpointError, .incompleteClientIdentity) }

        let endpoint = try amqpsEndpoint(
            "amqps://broker", clientCertificatePEM: "CERT", clientKeyPEM: "KEY")
        XCTAssertEqual(endpoint.clientCertificatePEM, "CERT")
        XCTAssertEqual(endpoint.clientKeyPEM, "KEY")
    }

    func testAmqpsGuardCarriesACustomCABundle() throws {
        // Rule 2 — the common case, and the reason nobody has a legitimate need
        // for rule 4 to be relaxed: an in-cluster broker's certificate is not
        // issued by a public CA.
        XCTAssertEqual(try amqpsEndpoint("amqps://broker", caPEM: "CA-PEM").caPEM, "CA-PEM")
        XCTAssertNil(try amqpsEndpoint("amqps://broker").caPEM)
    }

    func testAmqpsGuardStripsUserinfoFromTheHost() throws {
        // Credentials belong to the connection, not to this check — and leaving
        // them in `host` would put them wherever host is logged.
        let endpoint = try amqpsEndpoint("amqps://user:pass@broker.internal:5671/v")
        XCTAssertEqual(endpoint.host, "broker.internal")
        XCTAssertFalse(endpoint.host.contains("pass"))
    }

    func testAmqpsGuardKeepsAnIPv6LiteralIntact() throws {
        let endpoint = try amqpsEndpoint("amqps://[2001:db8::1]:5671/prod")
        XCTAssertEqual(endpoint.host, "2001:db8::1")
        XCTAssertEqual(endpoint.port, 5671)
    }

    func testAmqpsGuardFailsClosedOnAnUnusableEndpoint() {
        // A URL this cannot read is not a URL it can vouch for.
        for url in ["amqps://", "amqps://broker:0", "amqps://broker:99999",
                    "amqps://[2001:db8::1", "amqps://broker:notaport"] {
            XCTAssertThrowsError(try amqpsEndpoint(url), "\(url) must be refused")
        }
    }

    // MARK: - Helpers

    private func event(named name: ReactorEventName) -> ReactorEvent {
        ReactorEvent(
            tenantID: tenantID, event: name, correlationID: correlationID,
            payloadJSON: "{}", timeoutMilliseconds: 1000, nonce: "n")
    }
}

/// A mutable box, so a `@Sendable` handler closure can report back into a test.
/// The suite is single-threaded; the runtime awaits each handler before taking
/// the next delivery.
final class Box<T>: @unchecked Sendable {
    var value: T
    init(_ value: T) { self.value = value }
}

/// A transport that replays a fixed script and records what was published.
/// §22.13's runtime assertions are about COUNTS — zero published messages, never
/// an `allow` — so recording is the whole job.
actor RecordingReactorTransport: ReactorTransport {
    struct Published: Sendable {
        let destination: String
        let correlationID: String
        let body: Data
    }

    private let bodies: [Data]
    private let replyTo: String?
    private var at = 0
    private(set) var published: [Published] = []

    init(bodies: [Data], replyTo: String? = nil) {
        self.bodies = bodies
        self.replyTo = replyTo
    }

    func nextDelivery() async throws -> ReactorDelivery? {
        guard at < bodies.count else { return nil }
        defer { at += 1 }
        return ReactorDelivery(body: bodies[at], replyTo: replyTo)
    }

    func publishReply(destination: String, correlationID: String, body: Data) async throws {
        published.append(
            Published(destination: destination, correlationID: correlationID, body: body))
    }
}

extension Result where Success == ReactorEvent, Failure == ReactorRefusal {
    /// `nil` on success, the refusal otherwise — so an assertion reads as one
    /// line rather than as a `guard case`.
    var refusal: ReactorRefusal? {
        if case .failure(let why) = self { return why }
        return nil
    }
}
