import XCTest
import Crypto
@testable import AxiamSDK

/// The SSF receiver helper — CONTRACT.md §32.8's eight helper tests, plus discovery, the JWKS
/// failure posture and the RFC 8935 code mapping.
///
/// Every key is an Ed25519 key generated by the test from fresh randomness, and every SET is
/// signed here: no key literal, no captured token.
final class SsfReceiverTests: XCTestCase {

    private static let base = "https://iam.example.test"
    private static let issuer = "https://iam.example.test/t/22222222-2222-4222-8222-222222222222"
    private static let audience = "https://rp.example.test"
    private static var jwksURI: String { "\(base)/oauth2/jwks" }

    /// A run-time Ed25519 key and the SETs it signs.
    struct SetKey {
        let kid: String
        let seed: Data

        static func generate(kid: String? = nil) -> SetKey {
            SetKey(
                kid: kid ?? "k-\(SecretKit.random().prefix(16))",
                seed: Curve25519.Signing.PrivateKey().rawRepresentation)
        }

        private var privateKey: Curve25519.Signing.PrivateKey {
            try! Curve25519.Signing.PrivateKey(rawRepresentation: seed)
        }

        var jwk: [String: Any] {
            [
                "kty": "OKP", "crv": "Ed25519", "alg": "EdDSA", "use": "sig", "kid": kid,
                "x": TestBase64URL.encode(privateKey.publicKey.rawRepresentation),
            ]
        }

        func sign(header: [String: Any], claims: [String: Any]) -> String {
            let h = TestBase64URL.encode(try! JSONSerialization.data(withJSONObject: header))
            let p = TestBase64URL.encode(try! JSONSerialization.data(withJSONObject: claims))
            let input = h + "." + p
            let signature = try! privateKey.signature(for: Data(input.utf8))
            return input + "." + TestBase64URL.encode(signature)
        }

        func signSet(_ claims: [String: Any]) -> String {
            sign(header: ["alg": "EdDSA", "typ": "secevent+jwt", "kid": kid], claims: claims)
        }
    }

    private static func claims() -> [String: Any] {
        [
            "iss": issuer,
            "aud": audience,
            "iat": 1_791_500_000,
            "jti": SecretKit.random(),
            "txn": "t-1",
            "sub_id": ["format": "iss_sub", "iss": issuer, "sub": UUID().uuidString.lowercased()],
            "events": [
                SsfEventTypeURI.sessionRevoked: ["event_timestamp": 1_791_500_000],
            ] as [String: Any],
        ]
    }

    private static func with(_ claims: [String: Any], _ key: String, _ value: Any) -> [String: Any] {
        var copy = claims
        copy[key] = value
        return copy
    }

    private static func without(_ claims: [String: Any], _ key: String) -> [String: Any] {
        var copy = claims
        copy.removeValue(forKey: key)
        return copy
    }

    private static func jwksReply(_ keys: [SetKey]) -> RoutedTransport.Reply {
        .json(200, object: ["keys": keys.map { $0.jwk }])
    }

    private func makeClient(_ transport: RoutedTransport) async throws -> AxiamClient {
        let config = try AxiamConfig(
            baseURL: URL(string: Self.base)!,
            tenantID: UUID().uuidString.lowercased(),
            retryEnabled: true)
        let client = AxiamClient(config: config, transport: transport)
        await client._setRetryTestSeams(jitter: { 0 }, sleep: { _ in })
        return client
    }

    private func makeReceiver(
        _ transport: RoutedTransport,
        keySource: SsfKeySource? = nil,
        issuer: String = SsfReceiverTests.issuer,
        token: String? = "cc-\(SecretKit.random())",
        now: @escaping @Sendable () -> Date = { Date() }
    ) async throws -> SsfReceiver {
        let client = try await makeClient(transport)
        var configuration = SsfReceiverConfiguration(
            issuer: issuer,
            audience: Self.audience,
            keySource: keySource ?? .jwksURI(Self.jwksURI))
        if let token {
            configuration.accessTokenProvider = { Sensitive(token) }
        }
        return try SsfReceiver(client: client, configuration: configuration, now: now)
    }

    /// The reason `set` is refused for, failing the test (with a fixed text) otherwise.
    private func reason(_ receiver: SsfReceiver, _ set: String) async -> SetFailureReason? {
        do {
            _ = try await receiver.verifySet(set)
            XCTFail("expected the SET to be refused")
            return nil
        } catch let error as AxiamError {
            guard case .auth = error else {
                XCTFail("a SET refusal is an AuthError")
                return nil
            }
            return error.setFailureReason
        } catch {
            XCTFail("a SET refusal is an AxiamError")
            return nil
        }
    }

    // MARK: - 1. A valid SET verifies into its claims

    func testASetSignedByTheJwksKeyVerifiesIntoItsClaims() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        let receiver = try await makeReceiver(transport)

        let claims = Self.claims()
        let subID = try XCTUnwrap(claims["sub_id"] as? [String: String])
        let event = try await receiver.verifySet(key.signSet(claims))
        XCTAssertEqual(event.jti, claims["jti"] as? String)
        XCTAssertEqual(event.iat, 1_791_500_000)
        XCTAssertEqual(event.iss, Self.issuer)
        XCTAssertEqual(event.aud, .string(Self.audience))
        XCTAssertEqual(event.txn, "t-1")
        XCTAssertEqual(event.eventType, SsfEventTypeURI.sessionRevoked)
        XCTAssertEqual(event.event, .object(["event_timestamp": .int(1_791_500_000)]))
        XCTAssertEqual(event.subID, .object(subID.mapValues { ManagementJSON.string($0) }))

        // An `aud` array containing the audience verifies too, and so does the media-type
        // spelling of `typ`, in any case.
        let array = Self.with(Self.claims(), "aud", ["other", Self.audience])
        let set = key.sign(
            header: ["alg": "EdDSA", "typ": "Application/SecEvent+JWT", "kid": key.kid],
            claims: array)
        let second = try await receiver.verifySet(set)
        XCTAssertEqual(second.aud, .array([.string("other"), .string(Self.audience)]))
    }

    // MARK: - 2. typ, then alg

    func testAWrongTypOrAlgIsRefusedInThatOrder() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        let receiver = try await makeReceiver(transport)
        let claims = Self.claims()

        for header in [
            ["alg": "EdDSA", "kid": key.kid],
            ["alg": "EdDSA", "typ": "JWT", "kid": key.kid],
        ] {
            let refused = await reason(receiver, key.sign(header: header, claims: claims))
            XCTAssertEqual(refused, .invalidType)
        }

        let payload = TestBase64URL.encode(try JSONSerialization.data(withJSONObject: claims))
        let noneHeader = TestBase64URL.encode(Data(#"{"alg":"none","typ":"secevent+jwt"}"#.utf8))
        let algNone = await reason(receiver, "\(noneHeader).\(payload).")
        XCTAssertEqual(algNone, .invalidKey)

        let hsHeader = TestBase64URL.encode(try JSONSerialization.data(
            withJSONObject: ["alg": "HS256", "typ": "secevent+jwt", "kid": key.kid]))
        let hsInput = "\(hsHeader).\(payload)"
        let mac = HMAC<SHA256>.authenticationCode(
            for: Data(hsInput.utf8), using: SymmetricKey(size: .bits256))
        let hs = await reason(receiver, "\(hsInput).\(TestBase64URL.encode(Data(mac)))")
        XCTAssertEqual(hs, .invalidKey)

        let twoParts = await reason(receiver, "a.b")
        XCTAssertEqual(twoParts, .malformed)
        let garbage = await reason(receiver, "!!.@@.##")
        XCTAssertEqual(garbage, .malformed)
        let array = TestBase64URL.encode(Data("[1]".utf8))
        let notAnObject = await reason(receiver, "\(array).\(payload).")
        XCTAssertEqual(notAnObject, .malformed)
        XCTAssertTrue(transport.requests("/oauth2/jwks").isEmpty, "steps 1–3 need no key")
    }

    // MARK: - 3. Another key, a tampered payload

    func testAnotherKeyOrATamperedPayloadIsInvalidKey() async throws {
        let key = SetKey.generate()
        let rogue = SetKey.generate(kid: key.kid)
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        let receiver = try await makeReceiver(transport)

        let byRogue = await reason(receiver, rogue.signSet(Self.claims()))
        XCTAssertEqual(byRogue, .invalidKey)

        var parts = key.signSet(Self.claims()).split(separator: ".").map(String.init)
        parts[1] = TestBase64URL.encode(try JSONSerialization.data(
            withJSONObject: Self.with(Self.claims(), "txn", "x")))
        let tampered = await reason(receiver, parts.joined(separator: "."))
        XCTAssertEqual(tampered, .invalidKey)
    }

    // MARK: - 4. iss, aud

    func testAnotherIssuerOrAudienceIsRefused() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        let receiver = try await makeReceiver(transport)

        let otherIssuer = await reason(
            receiver, key.signSet(Self.with(Self.claims(), "iss", "https://iam.example.test")))
        XCTAssertEqual(otherIssuer, .invalidIssuer)
        let otherAudience = await reason(
            receiver, key.signSet(Self.with(Self.claims(), "aud", ["https://elsewhere.test"])))
        XCTAssertEqual(otherAudience, .invalidAudience)
    }

    // MARK: - 5. The claim-set rules

    func testExpSubTwoEventsOrAMissingJtiIatOrSubIDIsInvalidRequest() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        let receiver = try await makeReceiver(transport)

        let twoEvents: [String: Any] = [
            SsfEventTypeURI.accountDisabled: [String: Any](),
            SsfEventTypeURI.accountPurged: [String: Any](),
        ]
        let cases: [[String: Any]] = [
            Self.with(Self.claims(), "exp", 1_891_500_000),
            Self.with(Self.claims(), "sub", "u"),
            Self.with(Self.claims(), "events", twoEvents),
            Self.without(Self.claims(), "jti"),
            Self.with(Self.claims(), "jti", ""),
            Self.without(Self.claims(), "iat"),
            Self.without(Self.claims(), "sub_id"),
        ]
        for (index, claims) in cases.enumerated() {
            let refused = await reason(receiver, key.signSet(claims))
            XCTAssertEqual(refused, .invalidRequest, "case \(index)")
        }
    }

    // MARK: - 6. Replay, and the window's floor

    func testAReplayIsRefusedAndAShortWindowIsRefusedAtConfiguration() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        let receiver = try await makeReceiver(transport)

        let set = key.signSet(Self.claims())
        _ = try await receiver.verifySet(set)
        let again = await reason(receiver, set)
        XCTAssertEqual(again, .replayed)

        let client = try await makeClient(transport)
        let short = SsfReceiverConfiguration(
            issuer: Self.issuer, audience: Self.audience, keySource: .jwksURI(Self.jwksURI),
            replayWindow: 6 * 24 * 60 * 60)
        XCTAssertThrowsError(try SsfReceiver(client: client, configuration: short)) { error in
            guard case AxiamError.network(let network) = error else {
                return XCTFail("a configuration refusal is the local ValidationError")
            }
            XCTAssertTrue(network.isValidation)
        }
        XCTAssertEqual(SsfReceiver.minimumReplayWindow, 7 * 24 * 60 * 60)
    }

    func testTheMemoryStoreForgetsAJtiAfterTheWindow() async {
        let clock = TestNow()
        let store = InMemorySsfReplayStore(now: { clock.now })
        let first = await store.checkAndRecord(jti: "a", window: 60)
        let second = await store.checkAndRecord(jti: "a", window: 60)
        XCTAssertTrue(first)
        XCTAssertFalse(second)
        clock.advance(61)
        let afterTheWindow = await store.checkAndRecord(jti: "a", window: 60)
        XCTAssertTrue(afterTheWindow, "expired, so new again")
    }

    // MARK: - 7. One refetch per unknown kid, at most once a minute

    func testAnUnknownKidCostsOneRefetchAndASecondOneNone() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        let clock = TestNow()
        let receiver = try await makeReceiver(transport, now: { clock.now })

        _ = try await receiver.verifySet(key.signSet(Self.claims()))
        XCTAssertEqual(transport.requests("/oauth2/jwks").count, 1, "primes the cache")

        let stranger = await reason(receiver, SetKey.generate().signSet(Self.claims()))
        XCTAssertEqual(stranger, .invalidKey)
        XCTAssertEqual(transport.requests("/oauth2/jwks").count, 2, "exactly one refetch")

        clock.advance(30)
        let another = await reason(receiver, SetKey.generate().signSet(Self.claims()))
        XCTAssertEqual(another, .invalidKey)
        XCTAssertEqual(transport.requests("/oauth2/jwks").count, 2, "no refetch within the minute")

        clock.advance(31)
        let later = await reason(receiver, SetKey.generate().signSet(Self.claims()))
        XCTAssertEqual(later, .invalidKey)
        XCTAssertEqual(transport.requests("/oauth2/jwks").count, 3, "a minute later, one more")
    }

    func testAJwksFetchFailureIsANetworkErrorNotARefusal() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [.empty(503)])
        let receiver = try await makeReceiver(transport)

        do {
            _ = try await receiver.verifySet(key.signSet(Self.claims()))
            XCTFail("a JWKS that cannot be fetched cannot verify anything")
        } catch let error as AxiamError {
            guard case .network = error else { return XCTFail("expected a NetworkError") }
            XCTAssertNil(error.setFailureReason, "not a verdict on the SET")
        }
    }

    // MARK: - 8. poll

    func testPollPassesAckAndSetErrsThroughAndSortsTheAnswer() async throws {
        let key = SetKey.generate()
        let stream = UUID().uuidString.lowercased()
        let good = Self.claims()
        let bad = Self.with(Self.claims(), "iss", "https://impostor.test")
        let goodJTI = try XCTUnwrap(good["jti"] as? String)
        let badJTI = try XCTUnwrap(bad["jti"] as? String)
        let token = "cc-\(SecretKit.random())"

        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        transport.route("POST", "/ssf/v1/poll/\(stream)", [
            .json(200, object: [
                "sets": [goodJTI: key.signSet(good), badJTI: key.signSet(bad)],
                "moreAvailable": true,
            ] as [String: Any]),
        ])
        let receiver = try await makeReceiver(transport, token: token)

        let result = try await receiver.poll(
            streamID: stream,
            options: SsfPollOptions(
                maxEvents: 10,
                returnImmediately: true,
                ack: ["done-1", "done-2"],
                setErrs: ["old-1": SetErr(reason: .replayed)]))
        XCTAssertTrue(result.moreAvailable)
        XCTAssertEqual(result.events.map(\.jti), [goodJTI])
        XCTAssertEqual(result.refused, [RefusedSet(jti: badJTI, reason: .invalidIssuer)])

        let polls = transport.requests("/ssf/v1/poll/\(stream)")
        XCTAssertEqual(polls.count, 1)
        let body = try XCTUnwrap(polls[0].jsonBody)
        XCTAssertEqual(Set(body.keys), ["maxEvents", "returnImmediately", "ack", "setErrs"])
        XCTAssertEqual(body["maxEvents"] as? Int, 10)
        XCTAssertEqual(body["returnImmediately"] as? Bool, true)
        XCTAssertEqual(body["ack"] as? [String], ["done-1", "done-2"])
        let errs = try XCTUnwrap(body["setErrs"] as? [String: Any])
        XCTAssertEqual(Set(errs.keys), ["old-1"])
        let entry = try XCTUnwrap(errs["old-1"] as? [String: Any])
        XCTAssertEqual(Set(entry.keys), ["err"])
        XCTAssertEqual(entry["err"] as? String, "invalid_request")
        XCTAssertEqual(polls[0].headerValues("Authorization"), ["Bearer \(token)"])
        XCTAssertTrue(polls[0].headerValues("Cookie").isEmpty, "no SDK session")

        // A second poll with no arguments sends an empty object: still no ack.
        _ = try await receiver.poll(streamID: stream)
        let second = try XCTUnwrap(transport.requests("/ssf/v1/poll/\(stream)").last?.jsonBody)
        XCTAssertTrue(second.isEmpty, "nothing acknowledged on the caller's behalf")
    }

    /// §32.8 helper test 8's two-SET batch (contract 1.59, §34.2 P1; R-1, SW-2): the second SET
    /// names an unknown `kid` while the refetch fails. Afterwards the first SET's `jti` is not in
    /// the store, or the first SET is returned — never recorded and lost.
    func testABatchWhoseSecondSetCannotBeJudgedLosesNeitherSet() async throws {
        let key = SetKey.generate()
        let stranger = SetKey.generate()
        let stream = UUID().uuidString.lowercased()
        // `poll` judges in key order: "1-…" before "2-…".
        let firstJTI = "1-\(SecretKit.random())"
        let secondJTI = "2-\(SecretKit.random())"
        let first = Self.with(Self.claims(), "jti", firstJTI)
        let second = Self.with(Self.claims(), "jti", secondJTI)

        let transport = RoutedTransport()
        // The cache is primed by the first SET; the unknown kid's one refetch then fails.
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key]), .empty(503)])
        transport.route("POST", "/ssf/v1/poll/\(stream)", [
            .json(200, object: [
                "sets": [firstJTI: key.signSet(first), secondJTI: stranger.signSet(second)],
                "moreAvailable": false,
            ] as [String: Any]),
        ])
        let store = RecordingReplayStore()
        let client = try await makeClient(transport)
        var configuration = SsfReceiverConfiguration(
            issuer: Self.issuer, audience: Self.audience, keySource: .jwksURI(Self.jwksURI))
        configuration.accessTokenProvider = { Sensitive("cc-\(SecretKit.random())") }
        configuration.replayStore = store
        let receiver = try SsfReceiver(client: client, configuration: configuration)

        var returned: [String] = []
        do {
            let result = try await receiver.poll(streamID: stream)
            returned = result.events.map(\.jti)
            // This SDK's form of P1: the judged SET is returned, the rest listed unrecorded.
            XCTAssertEqual(returned, [firstJTI])
            XCTAssertEqual(result.unjudged, [secondJTI])
            XCTAssertNotNil(result.interruption)
            XCTAssertFalse(
                result.refused.map(\.jti).contains(secondJTI),
                "a SET whose key could not be fetched is not refused: no verdict was reached")
        } catch let error as AxiamError {
            XCTAssertNil(error.setFailureReason, "a failed key fetch is no verdict")
        }
        let recorded = await store.recorded
        XCTAssertTrue(
            returned.contains(firstJTI) || !recorded.contains(firstJTI),
            "the first SET was recorded and not returned: re-offered, it would read replayed")
        XCTAssertFalse(recorded.contains(secondJTI), "the unjudged SET is not recorded")
        XCTAssertFalse(returned.contains(secondJTI))
    }

    /// §32.7 step 9, §34.2 P3 – P4 (R-4, SW-4): a replay store that cannot answer fails
    /// CLOSED. The store reports the failure by throwing; `verifySet` then raises a
    /// `NetworkError` with no reason code — no verdict, no acceptance — and `poll` neither
    /// returns nor records the SET (P1), so the transmitter offers it again.
    func testAReplayStoreThatCannotAnswerRefusesAndRecordsNothing() async throws {
        let key = SetKey.generate()
        let stream = UUID().uuidString.lowercased()
        let goodJTI = "1-\(SecretKit.random())"
        let unanswerableJTI = "2-\(SecretKit.random())"
        let store = FailingReplayStore(failingOn: [unanswerableJTI])

        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        transport.route("POST", "/ssf/v1/poll/\(stream)", [
            .json(200, object: [
                "sets": [
                    goodJTI: key.signSet(Self.with(Self.claims(), "jti", goodJTI)),
                    unanswerableJTI: key.signSet(Self.with(Self.claims(), "jti", unanswerableJTI)),
                ],
                "moreAvailable": false,
            ] as [String: Any]),
        ])
        let client = try await makeClient(transport)
        var configuration = SsfReceiverConfiguration(
            issuer: Self.issuer, audience: Self.audience, keySource: .jwksURI(Self.jwksURI))
        configuration.accessTokenProvider = { Sensitive("cc-\(SecretKit.random())") }
        configuration.replayStore = store
        let receiver = try SsfReceiver(client: client, configuration: configuration)

        do {
            _ = try await receiver.verifySet(
                key.signSet(Self.with(Self.claims(), "jti", unanswerableJTI)))
            XCTFail("a store that cannot answer must not let the SET through")
        } catch let error as AxiamError {
            guard case .network = error else { return XCTFail("a store failure is a NetworkError") }
            XCTAssertNil(error.setFailureReason, "not a verdict on the SET")
        }

        let result = try await receiver.poll(streamID: stream)
        XCTAssertEqual(result.events.map(\.jti), [goodJTI])
        XCTAssertTrue(result.refused.isEmpty, "no verdict was reached on the second SET")
        XCTAssertEqual(result.unjudged, [unanswerableJTI])
        XCTAssertNotNil(result.interruption)
        let recorded = await store.recorded
        XCTAssertEqual(recorded, [goodJTI])
    }

    func testPollIsNotRetriedOn400() async throws {
        let transport = RoutedTransport()
        transport.route("POST", "/ssf/v1/poll/s-1", [.json(400, #"{"error": "push stream"}"#)])
        let receiver = try await makeReceiver(transport)

        do {
            _ = try await receiver.poll(streamID: "s-1")
            XCTFail("a 400 must surface")
        } catch AxiamError.network(let error) {
            XCTAssertTrue(error.isValidation)
        }
        XCTAssertEqual(transport.requests("/ssf/v1/poll/s-1").count, 1, "a retry-enabled client, one request")
    }

    func testAPolledSetUnderAnotherKeyAndANonStringSetAreRefused() async throws {
        let key = SetKey.generate()
        let claims = Self.claims()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        transport.route("POST", "/ssf/v1/poll/s-2", [
            .json(200, object: [
                "sets": ["not-its-jti": key.signSet(claims), "a-number": 42] as [String: Any],
                "moreAvailable": false,
            ] as [String: Any]),
        ])
        let receiver = try await makeReceiver(transport)

        let result = try await receiver.poll(streamID: "s-2")
        XCTAssertTrue(result.events.isEmpty)
        XCTAssertFalse(result.moreAvailable)
        XCTAssertEqual(
            result.refused,
            [
                RefusedSet(jti: "a-number", reason: .malformed),
                RefusedSet(jti: "not-its-jti", reason: .invalidRequest),
            ])
    }

    func testDiscoverySuppliesTheJwksURIAndMustNameTheIssuer() async throws {
        let key = SetKey.generate()
        let transport = RoutedTransport()
        transport.route("GET", "/oauth2/jwks", [Self.jwksReply([key])])
        transport.route("GET", "/.well-known/ssf-configuration", [
            .json(200, object: ["issuer": Self.issuer, "jwks_uri": Self.jwksURI]),
        ])
        let discovery = SsfKeySource.discoveryURL("\(Self.base)/.well-known/ssf-configuration")

        let receiver = try await makeReceiver(transport, keySource: discovery)
        _ = try await receiver.verifySet(key.signSet(Self.claims()))

        let wrong = try await makeReceiver(
            transport, keySource: discovery, issuer: "https://someone-else.test", token: nil)
        do {
            _ = try await wrong.verifySet(key.signSet(Self.claims()))
            XCTFail("a configuration naming another issuer must not be trusted")
        } catch let error as AxiamError {
            guard case .network = error else { return XCTFail("expected a NetworkError") }
            XCTAssertNil(error.setFailureReason)
        }

        // A poll with no token provider is refused locally.
        let before = transport.requests.count
        do {
            _ = try await wrong.poll(streamID: "s")
            XCTFail("no provider, no poll")
        } catch AxiamError.auth(_) {
            // expected
        }
        XCTAssertEqual(transport.requests.count, before, "nothing was sent")
    }

    func testThePushCodesAreRfc8935Codes() {
        let expected: [SetFailureReason: String] = [
            .malformed: "invalid_request",
            .invalidType: "invalid_request",
            .replayed: "invalid_request",
            .invalidKey: "invalid_key",
            .invalidIssuer: "invalid_issuer",
            .invalidAudience: "invalid_audience",
            .invalidRequest: "invalid_request",
        ]
        XCTAssertEqual(expected.count, SetFailureReason.allCases.count)
        for (reason, code) in expected {
            XCTAssertEqual(reason.pushErrorCode, code)
            XCTAssertEqual(SetErr(reason: reason).err, code)
        }
        XCTAssertEqual(SetFailureReason.replayed.rawValue, "replayed")
        XCTAssertEqual(SetFailureReason.invalidType.rawValue, "invalid_type")
    }
}

/// A replay store that remembers what it recorded, for the assertions on what `poll` keeps.
actor RecordingReplayStore: SsfReplayStore {
    private(set) var recorded: Set<String> = []

    func checkAndRecord(jti: String, window: TimeInterval) -> Bool {
        recorded.insert(jti).inserted
    }
}

/// A replay store that cannot answer for some `jti`s — a shared store that is down.
actor FailingReplayStore: SsfReplayStore {
    struct Unavailable: Error {}

    private let failingOn: Set<String>
    private(set) var recorded: Set<String> = []

    init(failingOn: Set<String>) {
        self.failingOn = failingOn
    }

    func checkAndRecord(jti: String, window: TimeInterval) throws -> Bool {
        if failingOn.contains(jti) { throw Unavailable() }
        return recorded.insert(jti).inserted
    }
}

/// A settable clock, readable from `@Sendable` closures.
final class TestNow: @unchecked Sendable {
    private let lock = NSLock()
    private var current = Date(timeIntervalSince1970: 1_800_000_000)

    var now: Date { lock.locked { current } }

    func advance(_ seconds: TimeInterval) {
        lock.locked { current = current.addingTimeInterval(seconds) }
    }
}
